.github/workflows/ci.yml

https://jira.camptocamp.com/browse/GSREN3D-219

GSREN3D-219: Fixing CI

---

.husky/pre-commit
index.html
src/App.vue
src/components/home/SidePanel.vue

https://jira.camptocamp.com/browse/GSREN3D-220
- also set the language
- I will test the accessibility with windows virtual box, but not included here (it will take more time)

GSREN3D-220: Make side panel non retractable and add precommit

---

src/App.vue
src/assets/icons/icon-tooltip-red.svg
src/assets/icons/icon-tooltip.svg
src/components/ui/UiButtonWithTooltip.story.vue
src/components/ui/UiButtonWithTooltip.vue

GSREN3D-226 - Create information button
https://jira.camptocamp.com/browse/GSREN3D-226

GSREN3D-226 - Create information button

---

src/App.vue
src/model/views.model.ts
src/router/index.ts
src/views/MapPCAETView.vue

https://jira.camptocamp.com/browse/GSREN3D-220
- Add Map PCAET view
- Make side panel non retractable on home view only

GSREN3D-220: Make panel retractable on home view only.

---

package-lock.json
package.json
src/components/map/CompassComponent.vue
src/components/map/buttons/NavigationButtons.vue
src/components/ui/UiSolarPanelTitle.vue
src/main.ts
src/views/HomeView.vue
src/views/MapPCAETView.vue

Use uicompass from common ui
JIRA issue
https://jira.camptocamp.com/browse/GSREN3D-276
Description
Merge this PR first : https://github.com/sigrennesmetropole/cooperation_jn_common_ui/pull/16

Use uicompass from common ui

---

src/App.vue
src/assets/icons/icon-multiply-amber.svg
src/assets/icons/icon-multiply.svg
src/components/home/ButtonWithCheckboxBegin.vue
src/components/ui/UiPopUpBottomInformation.vue
src/components/ui/UiSearchBar.vue
src/model/views.model.ts
src/router/index.ts
src/stores/address.ts
src/stores/views.ts
src/views/MapPCAETView.vue
src/views/RoofSelectionView.vue

GSREN3D-233 - popup click building
https://jira.camptocamp.com/browse/GSREN3D-233
Navigation between pages
Pop up click building

GSREN3D-233 - popup click building

---

src/App.vue
src/components/home/SidePanel.vue
src/components/map/MapComponent.vue
src/components/ui/UiButtonWithTooltip.vue
src/components/ui/UiPopUpBottomInformation.vue
src/stores/panels.ts
src/views/RoofSelectionView.vue

245 - Fix bugs right panel
https://jira.camptocamp.com/browse/GSREN3D-245
https://jira.camptocamp.com/browse/GSREN3D-240
Right panel : 
- no map under panel
- Compass display at the left of panel

245 - Fix bugs right panel

---

src/components/map/CompassComponent.vue

GSREN3D-306: fix compass rotattion map
https://jira.camptocamp.com/browse/GSREN3D-306

GSREN3D-306: fix compass rotattion map

---

package-lock.json
package.json
src/components/map/buttons/NavigationButtons.vue

GSREN3D-281 - describe compass
https://jira.camptocamp.com/browse/GSREN3D-281

GSREN3D-281 - describe compass

---

src/components/simulation/StepIllustration.vue

https://jira.camptocamp.com/browse/GSREN3D-241

GSREN3D-241: Remove alt="s"

---

src/components/map/CompassComponent.vue
src/services/RennesApp.ts
src/stores/map.ts

GSREN3D-306 -fix compass synchro
https://jira.camptocamp.com/browse/GSREN3D-306

GSREN3D-306 -fix compass synchro

---

src/App.vue
src/components/ui/UiChartDonut.vue

GSREN3D-235 : donut graph: add circle inside the donut to the 'surface favorable'
https://jira.camptocamp.com/browse/GSREN3D-235
Before change : 
After change:

GSREN3D-235 : donut graph: add circle inside the donut to the 'surface favorable'

---

src/components/simulation/SimulationResult.vue

https://jira.camptocamp.com/browse/GSREN3D-314

GSREN3D-314: Set 1 as the minimum number of solar panel.

---

src/components/simulation/StepDescription.vue

https://jira.camptocamp.com/browse/GSREN3D-349
Add more step description based on the current step and substep

GSREN3D-349: Add more step description based on the current step and substep.

---

src/components/ui/UiChartDonut.vue

GSREN3D-346 - delete label on hover of donut
https://jira.camptocamp.com/browse/GSREN3D-235

GSREN3D-235 - delete label on hover of donut

---

src/components/home/SidePanel.vue
src/components/simulation/FooterButtons.vue
src/views/StepSunshineView.vue

https://jira.camptocamp.com/browse/GSREN3D-289
fixed deleted div on stepSunshineView and new correction of the gap

289 margin patch on step sunshine view

---

src/assets/icons/icon-home.svg
src/components/legal/HeaderLegalNotice.vue
src/components/simulation/HeaderEndSimulation.vue
src/components/ui/UiHeaderFullScreen.story.vue
src/components/ui/UiHeaderFullScreen.vue
src/views/LegalNoticeView.vue

GSREN3D-365 - Simulation step 4: result page header
https://jira.camptocamp.com/browse/GSREN3D-365

GSREN3D-365 - Simulation step 4: result page header

---

src/components/chart/SurfaceChartDonut.vue
src/components/roof_selection/SurfaceNumber.vue
src/components/ui/UiChartDonut.vue
src/model/roof.model.ts
src/services/roofDataService.ts
src/services/selectRoofInteraction.ts
src/stores/roofData.ts

GSREN3D-361 - Data from roof on page roof-selected-information
https://jira.camptocamp.com/browse/GSREN3D-360
https://jira.camptocamp.com/browse/GSREN3D-361
https://user-images.githubusercontent.com/121813008/227973310-c04c0554-9098-47c9-8e6c-281680899822.mp4

GSREN3D-361 - Data from roof on page roof-selected-information

---

package-lock.json
package.json
src/components/home/ButtonWithCheckboxBegin.vue
src/components/simulation/BoxStep.story.vue
src/components/simulation/FooterButtons.vue
src/components/simulation/HeaderEndSimulation.vue
src/components/simulation/SetUpStep.vue
src/components/ui/UiSearchBar.vue
src/views/RoofSelectedInformation.vue

Font dm sans
https://jira.camptocamp.com/browse/GSREN3D-384

Font dm sans

---

src/components/legal/PrivacyLegal.vue

GSREN3D-379 - missing link 
https://jira.camptocamp.com/browse/GSREN3D-379

GSREN3D-379 - missing link 

---

package-lock.json
package.json
src/App.vue
src/assets/icons/icon-external-link-white.svg
src/components/home/ButtonWithCheckboxBegin.vue
src/components/home/TermsOfUsePopup.vue
src/components/ui/UiTooltipSunshine.vue
src/stores/popUpStore.ts

GSREN3D-390 - new design tooltip + open terms of use popup 
https://jira.camptocamp.com/browse/GSREN3D-390
First merge this PR on common : https://github.com/sigrennesmetropole/cooperation_jn_common_ui/pull/23
https://user-images.githubusercontent.com/121813008/229945711-bde7a0b0-e59c-4adf-8954-5f3d013e2d81.mp4

new design tooltip + open terms of use popup

---

src/components/home/ButtonWithCheckboxBegin.vue
src/components/map/MapComponent.vue
src/services/selectRoofInteraction.ts
src/services/viewsService.ts
src/stores/home.ts
src/views/HomeView.vue

GSREN3D-400 - Select building without address bar
https://jira.camptocamp.com/browse/GSREN3D-400
https://jira.camptocamp.com/browse/GSREN3D-396
https://user-images.githubusercontent.com/121813008/229938294-a40c3899-e04c-4a8e-a211-9a8002f49785.mp4

GSREN3D-400 - Select building without address bar

---

src/components/simulation/RoofAccordion.vue
src/components/simulation/SimulationResult.vue
src/model/solarPanel.model.ts

GSREN3D-404 - Fix some bugs
https://jira.camptocamp.com/browse/GSREN3D-404

GSREN3D-404 - Fix some bugs

---

src/components/search_bar/SearchBar.vue
src/components/simulation/CheckBox.vue

https://jira.camptocamp.com/browse/GSREN3D-415

fixes search bar

---

src/components/ui/UiDisclosure.story.vue
src/components/ui/UiDisclosure.vue
src/views/RoofSelectedInformation.vue

https://jira.camptocamp.com/browse/GSREN3D-XXX
update statistic design content

402- updated statistic design content

---

src/App.vue
src/components/ui/UiExplanationsStepSunshine.vue

GSREN3D-407 - use new tooltip
https://jira.camptocamp.com/browse/GSREN3D-407
https://jira.camptocamp.com/browse/GSREN3D-411

GSREN3D-407 - use new tooltip

---

package-lock.json
src/components/map/buttons/NavigationButtons.vue

https://jira.camptocamp.com/browse/GSREN3D-385
add data-title on UiIconButton

385- tooltip navigation buttons

---

src/components/simulation/SetUpStep.vue
src/tests/components/simulation/SetUpStep.spec.ts
src/tests/components/simulation/__snapshots__/SetUpStep.spec.ts.snap

https://jira.camptocamp.com/browse/GSREN3D-328
tests on SetUpStep component

328- simulation elements tests

---

src/components/simulation/StepIllustration.vue
src/tests/components/simulation/StepDescription.spec.ts
src/tests/components/simulation/StepIllustration.spec.ts
src/tests/components/simulation/StepTitle.spec.ts
src/tests/components/simulation/UiStepTitle.spec.ts
src/tests/components/simulation/WaitingAnimation.spec.ts
src/tests/components/simulation/__snapshots__/StepIllustration.spec.ts.snap
src/tests/components/simulation/__snapshots__/UiStepTitle.spec.ts.snap
src/tests/components/simulation/__snapshots__/WaitingAnimation.spec.ts.snap

https://jira.camptocamp.com/browse/GSREN3D-328
Add StepDescription, StepIllustration, StepTitle, UiStepTitle, WaitingAnimation tests

328- Add simulation tests

---

src/tests/components/simulation/SetUpStep.spec.ts
src/tests/components/simulation/__snapshots__/SetUpStep.spec.ts.snap

https://jira.camptocamp.com/browse/GSREN3D-328
fix test after merge

328- fix test after merge

---

src/components/home/ProcessSteps.vue
src/components/roof_selection/AddressTooltip.vue
src/components/ui/UiExplanationTooltip.story.vue

https://jira.camptocamp.com/browse/GSREN3D-446
change text on HomePage and typo on UiExplanationTooltip

446- text modification in HomePage and typo

---

src/components/simulation/ElectricityConsumptionManual.vue
src/components/simulation/StepDescription.vue
src/components/simulation/StepTitle.vue
src/tests/components/simulation/SetUpStep.spec.ts
src/tests/components/simulation/__snapshots__/ElectricityConsumptionManual.spec.ts.snap
src/tests/components/simulation/__snapshots__/SetUpStep.spec.ts.snap

https://jira.camptocamp.com/browse/GSREN3D-419
Change title, add description and add personal data text on step 3.3

419- Change stepTitle and add text on 3.3 simulation step

---

src/tests/components/simulation/StepDescription.spec.ts

https://jira.camptocamp.com/browse/GSREN3D-419
fix unit test on StepDescription component

419- fix unit test on StepDescription

---

src/components/simulation/ElectricityConsumptionButton.vue
src/stores/simulations.ts
src/tests/components/simulation/ElectricityConsumptionButton.spec.ts
src/tests/components/simulation/__snapshots__/ElectricityConsumptionButton.spec.ts.snap

https://jira.camptocamp.com/browse/GSREN3D-456
Add text on step3 and skip consumption information

456- Add text on step3 and skip consumption information

---

src/App.vue
src/components/results/ConsumptionInformation.vue
src/model/views.model.ts
src/router/index.ts
src/tests/components/results/ConsumptionInformation.spec.ts
src/views/SimulationResultsView.vue

https://jira.camptocamp.com/browse/GSREN3D-423
init simulation-results page and add consumption information component

423- simulation result page consumption information component

---

src/views/SimulationResultsView.vue

https://jira.camptocamp.com/browse/GSREN3D-423
remove component

423- remove component

---

package-lock.json
package.json
src/components/home/ProcessSteps.vue
src/components/simulation/ElectricityConsumptionManual.vue
src/tests/components/simulation/__snapshots__/ElectricityConsumptionManual.spec.ts.snap

-text footer 
-text : "Ma consommation annuelle est de :"
-text: "Estimez vos économies d'énergies"

Fix erased change

---

src/App.vue
src/components/map/buttons/NavigationButtons.vue
src/services/interactionUtils.ts
src/stores/autocalsol.ts
src/stores/views.ts
src/views/LegalNoticeView.vue
src/views/SimulationAutocalsolView.vue
src/views/SimulationResultsView.vue

Connect autocalsol result
When the result of autocalsol is good, display the result
https://user-images.githubusercontent.com/121813008/233953041-d8fe92ea-b221-4575-acb0-d4b1ed3edc23.mp4

Connect autocalsol result

---

src/components/map/buttons/NavigationButtons.vue

https://jira.camptocamp.com/browse/GSREN3D-440
Remove home from HomeView and RoofSelectionView

440- remove home from HomeView and RoofSelectionView

---

src/components/simulation/LargeFooter.vue

https://jira.camptocamp.com/browse/GSREN3D-431
Fix typo on Large Footer

431- fix typo

---

src/assets/icons/icon-information-grey.svg
src/components/results/EnergiesRennes.vue

https://jira.camptocamp.com/browse/GSREN3D-429
Add a background and icon on div in EnergiesRennes component

429- Add bg and icon to component

---

package-lock.json
package.json
src/components/map/buttons/NavigationButtons.vue

https://jira.camptocamp.com/browse/GSREN3D-439
Add zoom synchronization button which resets the zoom level to that of page load

439- Add zoom synchronization button

---

src/router/index.ts

https://jira.camptocamp.com/browse/GSREN3D-XXX

router after each

---

src/components/results/SunshineInformation.vue
src/interactions/selectRoofInteraction.ts

https://jira.camptocamp.com/browse/GSREN3D-407
https://jira.camptocamp.com/browse/GSREN3D-421

Some fixes

---

src/App.vue
src/components/simulation/FooterButtons.vue
src/components/simulation/LeaveButton.vue
src/router/index.ts
src/services/resetStores.ts
src/services/windowService.ts
src/stores/autocalsol.ts
src/stores/roof.ts
src/stores/simulations.ts
src/views/RoofSelectionView.vue

https://jira.camptocamp.com/browse/GSREN3D-460
Fixed the bug concerning the loading of "roof-selection" page when clicking on the "Quitter" and "Annuler" buttons and on page reload from browser

460- Quitter button bugged

---

src/components/ui/UiChartDonut.vue

https://jira.camptocamp.com/browse/GSREN3D-449
Remove hover effect on donut chart
https://user-images.githubusercontent.com/126822753/236404999-97e8a559-4715-4df9-bc95-4f8ab1b975b1.mp4

449- Remove hover effect on chart

---

src/components/ui/UiHeaderFullScreen.vue
src/stores/simulations.ts
src/tests/components/simulation/HeaderEndSimulation.spec.ts
src/tests/components/simulation/__snapshots__/HeaderEndSimulation.spec.ts.snap
src/views/SimulationAutocalsolView.vue
src/views/SimulationResultsView.vue
src/views/StepSunshineView.vue

https://jira.camptocamp.com/browse/GSREN3D-496
Add header on end-simulation view and simulation-results view

496- init header on end-simulation and simulation-results

---

src/components/ui/UiHeaderFullScreen.vue

https://jira.camptocamp.com/browse/GSREN3D-470
When user clicks on "Fermer button" it closes the tab

470- Close legal-notice on Fermer button

---

.eslintrc.cjs
package-lock.json
package.json
src/components/map/MapComponent.vue
src/helpers/rectangleGrid.ts
src/services/roofInteractionHelper.ts
src/stores/roof.ts

Grid to matrix

---

src/App.vue
src/components/home/ButtonWithCheckboxBegin.vue
src/router/index.ts
src/services/resetStores.ts
src/stores/address.ts
src/views/RoofSelectedInformation.vue
src/views/RoofSelectionView.vue
src/views/StepSunshineView.vue

https://jira.camptocamp.com/browse/GSREN3D-470
Add warning pop up on reload, next and previous from browser arrows

470- Add pop up on previous and next arrow in browser

---

src/router/index.ts
src/services/resetStores.ts
src/stores/views.ts

504 - From home page to roof selection page: we must keep the adress
https://jira.camptocamp.com/browse/GSREN3D-504
https://github.com/sigrennesmetropole/cooperation_jn_solar/assets/121813008/461a31f6-1897-40a1-b3a1-0ccff062442c

504 - From home page to roof selection page: we must keep the adress

---

src/map.config.json

GSREN3D-447 - Change oblique
https://jira.camptocamp.com/browse/GSREN3D-447
before: 
After

GSREN3D-447 - Change oblique

---

package-lock.json
package.json
src/App.vue
src/components/map/MapComponent.vue
src/services/roofInteractionHelper.ts
src/stores/map.ts
src/worker/index.ts
src/worker/worker.ts
tests/setup.js

https://jira.camptocamp.com/browse/GSREN3D-505
use webworker to compute grid
add spinner during compute

Webworker spinner gridcompute

---

src/views/RoofSelectionView.vue
src/views/StepSunshineView.vue

https://jira.camptocamp.com/browse/GSREN3D-441
Fix navigation when user click on return button on AutocalsolView and ResultsView

441- Fix regression about navigation from AutocalsolView

---

src/services/solarPanel.spec.ts
src/services/solarPanel.ts
src/views/StepSunshineView.vue

https://jira.camptocamp.com/browse/GSREN3D-487
- Smooth way to hide and show solar panel
- Do not show green highlight when the solar panel is shown

GSREN3D-487: Polish Solar Panel Placement

---

src/App.vue
src/components/map/MapComponent.vue
src/components/simulation/ElectricityConsumptionManual.vue
src/components/simulation/InformationsLinky.vue
src/model/views.model.ts
src/router/index.ts
src/services/api-enedis-dataconnect.ts
src/services/api.ts
src/services/enedisService.ts
src/stores/districtInformations.ts
src/stores/enedis.ts
src/stores/interactions.ts
src/views/RedirectionEnedisView.vue
src/views/RoofSelectionView.vue
src/views/StepSunshineView.vue

GSREN3D-416 - Enedis prod
https://jira.camptocamp.com/browse/GSREN3D-416
PR BACK : https://github.com/sigrennesmetropole/cooperation_jn_backend/pull/17
- The user click on enedis
- For now we have one error 500 on the website of enedis, one ticket on the support of enedis is open 
- The user is redirect to the website, i simulate that by directly paste the url 
- We get the annual consumption of user in the page redirection-enedis 
- The user is redirect to the manual input with the value set 
https://github.com/sigrennesmetropole/cooperation_jn_solar/assets/121813008/9139dfaf-b5e8-4ccb-8320-b943b9a3c34d

GSREN3D-416 - Enedis prod

---

src/algorithm/solarPanelPlacement.ts
src/components/map/MapComponent.vue
src/services/roofInteractionHelper.ts
src/tests/algorithm/__tests__/solarPanelPlacement.spec.ts

https://jira.camptocamp.com/browse/GSREN3D-487
- Add unit test for big roof with obstacle solar panel placement
- Investigate the real issue
- Make an improvement
- Address: 10 Rue Jean Macé
- Roof: no 10 (not too big not too small)
- With and without obstacles
Without obstacles
```
MapComponent.vue:161 roofsStore.saveCleanMatrix(): 162.39999997615814
MapComponent.vue:162 substractSelectedSquaresFromGrid(roofsStore.gridMatrix!): 14
MapComponent.vue:165 solarPanelPlacement(roofsStore.gridMatrix!): 63.10000002384186
MapComponent.vue:166 mapStore.activate3d(): 636.5
MapComponent.vue:167 solarPanelGridToSolarPanelModel: 441.7999999821186
MapComponent.vue:168 Full setupSolarPanel: 1317.8999999761581
MapComponent.vue:213 setupSolarPanel: 1333.9000000059605
MapComponent.vue:214 …
```

GSREN3D-487: Solar panel placement performance

---

package-lock.json
package.json
src/assets/icons/delete-square.svg
src/components/home/ButtonWithCheckboxBegin.vue
src/components/home/TermsOfUsePopup.vue
src/components/search_bar/FiltersSearch.vue
src/components/simulation/InformationsEnergySaving.vue
src/components/simulation/RoofInformationsBox.vue
src/components/simulation/StepDescription.vue
src/components/simulation/StepIllustration.vue
src/components/ui/UiDisclosure.vue
src/tests/components/search_bar/__snapshots__/FiltersSearch.spec.ts.snap
src/tests/components/simulation/__snapshots__/InformationsEnergySaving.spec.ts.snap
src/tests/components/simulation/__snapshots__/StepIllustration.spec.ts.snap
src/views/RoofSelectedInformation.vue

https://jira.camptocamp.com/browse/GSREN3D-462
design corrections

462- Design corrections on several elements

---

package-lock.json
package.json

https://jira.camptocamp.com/browse/GSREN3D-515

common version 0.0.28

---

README.md
package-lock.json
package.json
src/App.vue
src/views/RoofSelectedInformation.vue
src/views/RoofSelectionView.vue

https://jira.camptocamp.com/browse/GSREN3D-516
https://jira.camptocamp.com/browse/GSREN3D-517
https://jira.camptocamp.com/browse/GSREN3D-501
Modification of z-index en several components
Fix display of TermsOfUsePopup

516- Modification of z-index en several components

---

src/components/search_bar/FiltersSearch.vue
src/tests/components/search_bar/__snapshots__/FiltersSearch.spec.ts.snap

https://jira.camptocamp.com/browse/GSREN3D-462
fix margin on FilterSearchComponent

462- Fix marging on FilterSearchComponent

---

src/interactions/selectRoofInteraction.ts

https://jira.camptocamp.com/browse/GSREN3D-525

click on building add spinner

---

src/components/search_bar/SearchBar.vue
src/services/api-sitesorg.ts
src/tests/services/api-sitesorg.spec.ts

GSREN3D-523-  [organization search] list of choices incomplete
https://jira.camptocamp.com/browse/GSREN3D-523
Search organism:
- Add city after the name 
- Fix bug on call api

GSREN3D-523-  [organization search] list of choices incomplete

---

src/components/map/MapComponent.vue
src/components/map/buttons/NavigationButtons.vue
src/services/RennesApp.ts
src/stores/map.ts

fix bug button reset zoom
https://jira.camptocamp.com/browse/GSREN3D-522
- Before page step-sunshine the reset zoom button go to home view point 
- Fix bug: after the swith between 2D and 3D the reset button didn't work

fix bug button reset zoom

---

src/views/RoofSelectedInformation.vue

https://jira.camptocamp.com/browse/GSREN3D-527
change 1200 to 1000

527- Fix display number on RoofSelectedInformation

---

src/components/map/MapComponent.vue

https://jira.camptocamp.com/browse/GSREN3D-513
Add a spinner on the solar panel result step.

GSREN3D-513: Add spinner on the solar panel result step.

---

src/components/map/DistrictDataTooltip.vue

district tooltip display at left if not enough space
https://jira.camptocamp.com/browse/GSREN3D-526
https://github.com/sigrennesmetropole/cooperation_jn_solar/assets/121813008/ecf00506-4910-4d4c-86dd-d33cf6a37fef

district tooltip display at left if not enough space

---

src/components/home/SidePanel.vue
src/components/simulation/FooterButtons.vue
src/components/simulation/LeaveButton.vue
src/components/simulation/SimulationSteps.vue
src/views/StepSunshineView.vue

right panel add scroolbar and fix footer
https://jira.camptocamp.com/browse/GSREN3D-464
https://github.com/sigrennesmetropole/cooperation_jn_solar/assets/121813008/794f21f8-d0bb-4489-9933-f61bc63e09d6

right panel add scroolbar and fix footer

---

src/components/home/TermsOfUsePopup.vue

https://jira.camptocamp.com/browse/GSREN3D-530
Fix text (missing "politique") and link to /legalnotice/confidentialite

530- Fix text and link in TermsOfUsePopup

---

src/components/home/TermsOfUsePopup.vue

https://jira.camptocamp.com/browse/GSREN3D-531

GSREN3D-531: Add copyright symbol.

---

.github/workflows/check-common-version.yml
package.json

https://jira.camptocamp.com/browse/GSREN3D-509
Error when the version of common ui is not the latest :
Message when the version of common ui is the latest :

check common version workflow

---

src/assets/icons/pin-white.svg
src/components/search_bar/SearchBar.vue
src/interactions/selectRoofInteraction.ts
src/map.config.json
src/services/searchBarService.ts
src/stores/layers.ts

https://jira.camptocamp.com/browse/GSREN3D-532

try add pin on address

---

src/services/searchBarService.ts
src/views/RoofSelectedInformation.vue

https://jira.camptocamp.com/browse/GSREN3D-XXX

hidde pin on selected information step

---

src/components/legal/CookiesLegal.vue
src/components/legal/HeaderLegalNotice.vue
src/components/legal/PrivacyLegal.vue
src/components/legal/SiteMap.vue

https://jira.camptocamp.com/browse/GSREN3D-530
Update informations on legal-notice view and add tiny fix

530- Update informations on legal-notice view

---

src/App.vue
src/components/map/DistrictDataTooltip.vue
src/components/map/InstallationDataTooltip.vue
src/interactions/selectDistrictInteractions.ts
src/stores/installations.ts

https://jira.camptocamp.com/browse/GSREN3D-548
New installationDataTooltip component and link with the installationsStore

548- InstallationDataTooltip component

---

src/components/legal/PrivacyLegal.vue

https://jira.camptocamp.com/browse/GSREN3D-530
Fix link

530- Fix link

---

src/components/legal/PrivacyLegal.vue

https://jira.camptocamp.com/browse/GSREN3D-530
Fix link on privacyLegal vue

530- Fix link on privacyLegal vue

---

src/components/chart/SurfaceChartDonut.vue
src/components/roof_selection/NoRoofOnBuilding.vue
src/components/roof_selection/SurfaceNumber.vue
src/components/simulation/RoofAccordion.story.vue
src/components/simulation/SimulationResult.story.vue
src/components/ui/UiChartDonut.vue
src/model/roof.model.ts
src/tests/components/simulation/RoofAccordion.spec.ts
src/tests/components/simulation/RoofAccordionOptions.spec.ts
src/tests/components/simulation/RoofInformationsBox.spec.ts
src/tests/components/simulation/SetUpStep.spec.ts
src/views/RoofSelectedInformation.vue

Fix statistics building
https://jira.camptocamp.com/browse/GSREN3D-552
https://jira.camptocamp.com/browse/GSREN3D-553
BEFORE 
AFTER

Fix statistics building

---

src/components/home/ButtonWithCheckboxBegin.vue

https://jira.camptocamp.com/browse/GSREN3D-564
Change text color and bold

564- Change text color

---

src/components/map/DistrictDataTooltip.vue
src/components/map/DistrictDisplayButton.vue

https://jira.camptocamp.com/browse/GSREN3D-551
https://jira.camptocamp.com/browse/GSREN3D-554
Fix design on districtTooltip and text button

551- Fix design on districtTooltip and change text button

---

src/components/map/MapComponent.vue
src/services/configService.ts
src/services/roofInteractionHelper.ts
src/services/solarPanel.ts
src/stores/config.ts
src/stores/roof.ts
src/tests/config/configuration_test.json
src/views/RedirectionEnedisView.vue
src/worker/worker.ts

inclinaison solar panel on flat roof
https://jira.camptocamp.com/browse/GSREN3D-561
In the case of flat roof (that mean the anamorphose is >= 98) 
The solar panel must be inclined at an angle of 20 degrees.
The azimuth must be 180 (South)
That inclination has to be made as a parameter stored in the config file
PR Back : https://github.com/sigrennesmetropole/cooperation_jn_backend/pull/35

inclinaison solar panel on flat roof

---

src/algorithm/solarPanelPlacement.ts
src/components/map/MapComponent.vue
src/services/configService.ts
src/services/roofInteractionHelper.ts
src/stores/config.ts
src/tests/algorithm/__tests__/solarPanelPlacement.spec.ts
src/tests/config/configuration_test.json
src/views/RedirectionEnedisView.vue
src/worker/worker.ts

config grid 
https://jira.camptocamp.com/browse/GSREN3D-559
https://jira.camptocamp.com/browse/GSREN3D-560
Grid square size: put the size as a parameter in the config file
3D solar panel: put the size as a parameter in the config file
PR Back : https://github.com/sigrennesmetropole/cooperation_jn_backend/pull/34

config grid

---

src/interactions/selectInstallationsInteraction.ts
src/services/installationService.ts

https://jira.camptocamp.com/browse/GSREN3D-547
- pictogram size change
- cursor pointer on hover

547- Design changes

---

README.md
src/components/simulation/SimulationResult.vue

https://jira.camptocamp.com/browse/GSREN3D-557
Change text size on simulation result component

557- kWc text size

---

src/components/map/MapComponent.vue
src/services/RennesApp.ts
src/services/searchBarService.ts
src/services/solarPanel.ts

https://jira.camptocamp.com/browse/GSREN3D-546

solar panel placement + icon address eye off set

---

src/components/map/MapComponent.vue
src/services/RennesApp.ts

GSREN3D-568 - in 2d when return on step 1/1 the 3D is not diplay
https://jira.camptocamp.com/browse/GSREN3D-568

GSREN3D-568 - in 2d when return on step 1/1 the 3D is not diplay

---

src/map.config.json

https://jira.camptocamp.com/browse/GSREN3D-565
Display grey color during tiles are loading

565- Change color when tiles are missing

---

src/tests/config/configuration_test.json

https://jira.camptocamp.com/browse/GSREN3D-584
change values into config file

584- Change values into config file

---

src/components/legal/AccessibilityLegal.vue
src/constants/legalLinks.ts

https://jira.camptocamp.com/browse/GSREN3D-587
Change text about accessibility

587- Change text of accessibility

---

src/model/roof.model.ts

round surface favorable
https://jira.camptocamp.com/browse/GSREN3D-585
surface are now round 1 digit after the comma 
Example : 
98.98 => 99 
97.32 => 97.4
44.58 => 44.6

round surface favorable

---

src/services/configService.ts
src/tests/components/map/MapComponent.spec.ts

https://jira.camptocamp.com/browse/GSREN3D-584
Remove default configuration

584- Remove default config

---

src/components/map/MapComponent.vue
src/components/map/buttons/NavigationButtons.vue
src/services/interactionUtils.ts

https://jira.camptocamp.com/browse/GSREN3D-558
Restrict zoom in on step sunshine view (when solar panels are visible)

558- Restrict zoom in step sunshine

---

src/views/SimulationAutocalsolView.vue

https://jira.camptocamp.com/browse/GSREN3D-586

autocalsol on flat roof

---

src/App.vue

https://jira.camptocamp.com/browse/GSREN3D-590
Add async method on config store call 

590- Adding async method on config store call

---

src/components/simulation/ElectricityConsumptionButton.vue
src/tests/components/simulation/ElectricityConsumptionButton.spec.ts

https://jira.camptocamp.com/browse/GSREN3D-597
Disable the Linky button

597- Disable linky button

---

src/components/simulation/ElectricityConsumptionButton.vue

https://jira.camptocamp.com/browse/GSREN3D-597
Add a tooltip when we click on Enendis button

597- Add tooltip on click

---

.github/dependabot.yml
src/components/home/TermsOfUsePopup.vue
src/components/map/buttons/NavigationButtons.vue

https://jira.camptocamp.com/browse/GSREN3D-641
https://jira.camptocamp.com/browse/GSREN3D-639
- Change text when user hover the navigation reset zoom button and the home navigation button
- Change text on CGU page

641- Change hover navigation text and cgu text

---

package-lock.json
package.json
src/components/results/ProductionInformationText.vue

https://jira.camptocamp.com/browse/GSREN3D-643

GSREN3D-643: Fix rounding issue.

---

src/services/viewPointHelper.spec.ts
src/services/viewPointHelper.ts

https://jira.camptocamp.com/browse/GSREN3D-598
- Let vc map core recompute the camera position and height of the group position.

GSREN3D-598: Fix zoom issue on some locations

---

README.md
src/components/home/TermsOfUsePopup.vue
src/components/legal/AccessibilityLegal.vue
src/components/legal/CookiesLegal.vue
src/components/legal/LegalNotice.vue
src/components/legal/PrivacyLegal.vue
src/constants/legalLinks.ts

https://jira.camptocamp.com/browse/GSREN3D-444
update footer content

444- Update tiny elements on footer

---

src/components/results/NeighbourhoodData.vue

https://jira.camptocamp.com/browse/GSREN3D-653

GSREN3D-653: Add explanation under the graph.

---

src/components/legal/SiteMap.vue

https://jira.camptocamp.com/browse/GSREN3D-444

GSREN3D-444: Add en construction on site map

---

src/components/simulation/ElectricityConsumptionButton.vue

https://jira.camptocamp.com/browse/GSREN3D-648

GSREN3D-648: Remove linky button.

---

src/components/simulation/LargeFooter.vue

https://jira.camptocamp.com/browse/GSREN3D-638

GSREN3D-638: Remove text on the simulation result page.

---

src/map.config.json
src/services/searchBarService.ts

https://jira.camptocamp.com/browse/GSREN3D-640
Sample (60 mail François Mitterrand, Rennes):
On a very tall building (18 rue de Brest, Rennes):
From a good angle, the line and the pin are visible
From behind, only the pin is visible

GSREN3D-640: Add line to pin

---

src/services/api-rva.ts
src/services/api-sitesorg.ts
src/tests/services/api-enedis-district.spec.ts
src/tests/services/api-rva.spec.ts
src/tests/services/api-sitesorg.spec.ts

https://jira.camptocamp.com/browse/GSREN3D-599
- Make sure this PR is merged and deployed first https://github.com/sigrennesmetropole/cooperation_jn_backend/pull/42

GSREN3D-599: Hide rva siteorg keys

---

src/components/legal/PrivacyLegal.vue

https://jira.camptocamp.com/browse/GSREN3D-655

GSREN3D-655: Update text.
